name: "Application testing"
on:
  workflow_call:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt libraries
        run: sudo apt install gettext -y

      - name: Setup Node.js version from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install yarn
        run: npm install -g yarn

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --silent

      - name: Install translations
        run: yarn localize

      - name: Run jest tests
        run: yarn test

      - name: Run typescript tests
        run: npx tsc
