name: "Master Workflow"

on:
  workflow_call:
    inputs:
      branch:
        description: "Branch to use for testing"
        required: false
        default: "master"
        type: string
      languages:
        description: "Languages to analyze"
        required: false
        default: '["javascript-typescript"]'
        type: string
      build_mode:
        description: "Build mode for CodeQL analysis"
        required: false
        default: "none"
        type: string

jobs:
  run-tests:
    uses: EyeSeeTea/github-workflows/.github/workflows/app-test.yml@${{ inputs.branch }}

  codeql-security-scan:
    needs: run-tests
    uses: EyeSeeTea/github-workflows/.github/workflows/codeql.yml@${{ inputs.branch }}
    with:
      languages: ${{ inputs.languages }}
      build_mode: ${{ inputs.build_mode }}

  bundlemon-size-check:
    needs: run-tests
    uses: EyeSeeTea/github-workflows/.github/workflows/bundlemon-build-size.yml@${{ inputs.branch }}
