name: "Master Workflow"

on:
  workflow_call:
    inputs:
      languages:
        description: "Languages to analyze"
        required: false
        default: '["javascript-typescript"]'
        type: string
      build_mode:
        description: "Build mode for CodeQL analysis"
        required: false
        default: "none"
        type: string

jobs:

  bundlemon-size-check:
    uses: ./.github/workflows/bundlemon-build-size.yml

